---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxx-postgresql-configuration
  labels:
    app: postgresql
    instance: xxx
data:
  postgresql.conf: |
    listen_addresses='*'
    checkpoint_completion_target=0.9
    wal_buffers=16MB
    autovacuum_analyze_scale_factor=0.002
    autovacuum_vacuum_scale_factor=0.001
    log_min_duration_statement = 5000
  pg_hba.conf: |
    local all all trust
    host all all localhost trust
    host all all 0.0.0.0/0 md5
    host replication repl_user 0.0.0.0/0 md5

