---
apiVersion: v1
kind: Service
metadata:
  name: xxx-postgresql-headless
  labels:
    app: postgresql
    instance: xxx
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    instance: xxx