---
apiVersion: v1
kind: Secret
metadata:
  name: xxx-postgresql
  labels:
    app: postgresql
    instance: xxx
type: Opaque
data:
  postgresql-password: "bnljc2s4TkxndVhZRGtHcDYzNnc=" ## nycsk8NLguXYDkGp636w
  postgresql-replication-password: "bnljc2s4TkxndVhZRGtHcDYzNnc="
