---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: postgresql
    component: pgadmin
    instance: fi862
  name: fi862-postgresql-pgadmin
data:
  servers.json: |
    {
      "Servers": {
          "1": {
              "Name": "fi862",
              "Group": "Servers",
              "Port": 5432,
              "Username": "postgres",
              "Host": "fi862-postgresql-headless",
              "SSLMode": "prefer",
              "MaintenanceDB": "postgres"
              }
      }
    }

