apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-tuan
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc
