apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
    svc: grafana-svc
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    name: grafana
    port: 3000
    targetPort: 3000
