apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-failed
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'echo the app is running!']
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', 'exit 1']
