apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: ct-nginx
        image: nginx:1.15.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 128M
          limits:
            cpu: 250m
            memory: 256M
