apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-side-vol
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - name: log-sider
        image: busybox
        command: ['sh', '-c', "while true; do echo sync app logs >> /cache/log-sider.log ; sleep 20; done"]
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi
