apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-add-init
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: log-sider
        image: busybox
        command: ['sh', '-c', "while true; do echo sync app logs; sleep 20; done"]
      initContainers:
        - name: mydb-init-available
          image: busybox
          command: ['sh', '-c', "until nslookup mydb-service.default.svc.cluster.local; do echo waiting for database; sleep 4; done"]
