apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bb
    spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: bb
        ports:
        - containerPort: 9091
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumeMounts:
        - name: config-vol1
          mountPath: "/config"
          readOnly: true
        - name: secret-vol1
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
      - name: config-vol1
        configMap:
          name: configmap1
          items:
          - key: "file1"
            path: "file1"
          - key: "file2"
            path: "file2"
      - name: secret-vol1
        secret:
          secretName: secret1
