apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # dạng key-value bình thường, gồm 1 key và 1 value dạng text
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # dạng key-value kiểu file, với key là tên file và value là nội dung file
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
